In [21]:
import numpy as np
import pandas as pd

df = pd.read_excel("P:/IndusTech/Pune_MIDC_Companies_FINAL.xlsx")

In [22]:
df

,company_name,address,midc_area,industry_label,business_type,latitude,longitude,phone,website,rating,total_reviews
0,220/132/33 KV MSETCL Baramati Substation,"R 59, Baramati Midc, Maharashtra Industrial De...",Baramati,General Manufacturing,Manufacturer,18.180788,74.602657,NaN,NaN,4.4,5.0
1,3D SculpLab - Online Manufacturing Service,"205, Satyam Bldg., Waghire Heights, behind Nav...",Baramati,General Manufacturing,Manufacturer,18.608438,73.802267,079759 44394,https://www.3dsculplab.xyz/,5.0,31.0
2,3WD Software,"Office No. 3, 4th floor, Mukti Corporate Plazz...",Baramati,Electronics Manufacturing,Manufacturer,18.157017,74.581319,088080 89975,http://www.3wdsoft.com/,4.5,21.0
3,5 Elements Organic,"Shop No.04, Plot No.6, 5H28+CG9 5/A, Jagtap Ma...",Baramati,Food Processing,Manufacturer,18.151077,74.566369,NaN,NaN,NaN,NaN
4,7 Plus Electronics,"5JG4+4M5, Mandai Rd, Suryanagari, Maharashtra ...",Baramati,Electronics Manufacturing,Manufacturer,18.175233,74.606676,099752 63923,NaN,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
5997,Yakotec Automation Technology Co. Ltd ( India),"Plot A-22/10, near Marriott Hotel, Phase II, I...",Talegaon,General Manufacturing,Manufacturer,18.753232,73.784557,089563 67783,NaN,5.0,2.0
5998,YASH ENTERPRISES,"Mantra City 360, opp. of Laa Fitness, Talegaon...",Talegaon,General Manufacturing,Manufacturer,18.725634,73.670915,099756 56156,NaN,NaN,NaN
5999,York Transport Equipment (I) Pvt. Ltd.,"RP43+M76, Gat no. 537 & 538, Badhalwadi, Vill....",Talegaon,IT Services,Manufacturer,18.806313,73.698776,NaN,http://www.yorktransport.com/,4.4,37.0
6000,ZTRIC India Pvt. Ltd,"21A, behind Amar Business Zone, near Anjor Soc...",Talegaon,Renewable Energy,Manufacturer,18.562251,73.775807,NaN,http://www.ztric.com/,4.6,35.0
6001,साई फॅब्रिकेशन,"बायपास, Vithalwadi, Pune, Dehu, Maharashtra 41...",Talegaon,General Manufacturing,Manufacturer,18.708714,73.772377,097622 54940,NaN,5.0,1.0

In [23]:
df["valid_phone_no"] = df["phone"].isnull()

In [24]:
df["valid_phone_no"] = df["valid_phone_no"].replace({True: "No", False: "Yes"})

In [20]:
# Drop the phone column and save the cleaned DataFrame to Excel
df.drop(columns=["phone"], inplace=True)
df.to_excel("P:/IndusTech/Pune_MIDC_Companies_FINAL_valid_phone.xlsx", index=False)

In [ ]:
import os

# Save as CSV
out_path = r"P:\IndusTech\Pune_MIDC_Companies_FINAL_valid_phone.csv"

# Make sure the folder exists
os.makedirs(os.path.dirname(out_path), exist_ok=True)

# Save the cleaned DataFrame to CSV
df.to_csv(out_path, index=False)

PermissionError: [Errno 13] Permission denied: 'P:/IndusTech/Pune_MIDC_Companies_FINAL_valid_phone.xlsx'

In [26]:
df

,company_name,address,midc_area,industry_label,business_type,latitude,longitude,phone,website,rating,total_reviews,valid_phone_no
0,220/132/33 KV MSETCL Baramati Substation,"R 59, Baramati Midc, Maharashtra Industrial De...",Baramati,General Manufacturing,Manufacturer,18.180788,74.602657,NaN,NaN,4.4,5.0,No
1,3D SculpLab - Online Manufacturing Service,"205, Satyam Bldg., Waghire Heights, behind Nav...",Baramati,General Manufacturing,Manufacturer,18.608438,73.802267,079759 44394,https://www.3dsculplab.xyz/,5.0,31.0,Yes
2,3WD Software,"Office No. 3, 4th floor, Mukti Corporate Plazz...",Baramati,Electronics Manufacturing,Manufacturer,18.157017,74.581319,088080 89975,http://www.3wdsoft.com/,4.5,21.0,Yes
3,5 Elements Organic,"Shop No.04, Plot No.6, 5H28+CG9 5/A, Jagtap Ma...",Baramati,Food Processing,Manufacturer,18.151077,74.566369,NaN,NaN,NaN,NaN,No
4,7 Plus Electronics,"5JG4+4M5, Mandai Rd, Suryanagari, Maharashtra ...",Baramati,Electronics Manufacturing,Manufacturer,18.175233,74.606676,099752 63923,NaN,3.0,2.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
5997,Yakotec Automation Technology Co. Ltd ( India),"Plot A-22/10, near Marriott Hotel, Phase II, I...",Talegaon,General Manufacturing,Manufacturer,18.753232,73.784557,089563 67783,NaN,5.0,2.0,Yes
5998,YASH ENTERPRISES,"Mantra City 360, opp. of Laa Fitness, Talegaon...",Talegaon,General Manufacturing,Manufacturer,18.725634,73.670915,099756 56156,NaN,NaN,NaN,Yes
5999,York Transport Equipment (I) Pvt. Ltd.,"RP43+M76, Gat no. 537 & 538, Badhalwadi, Vill....",Talegaon,IT Services,Manufacturer,18.806313,73.698776,NaN,http://www.yorktransport.com/,4.4,37.0,No
6000,ZTRIC India Pvt. Ltd,"21A, behind Amar Business Zone, near Anjor Soc...",Talegaon,Renewable Energy,Manufacturer,18.562251,73.775807,NaN,http://www.ztric.com/,4.6,35.0,No
6001,साई फॅब्रिकेशन,"बायपास, Vithalwadi, Pune, Dehu, Maharashtra 41...",Talegaon,General Manufacturing,Manufacturer,18.708714,73.772377,097622 54940,NaN,5.0,1.0,Yes